---
apiVersion: v1
kind: Template
metadata:
  name: ${APP}-${COMPONENT}
labels:
  app: ${APP}
  component: ${COMPONENT}
parameters:
  - name: APP
    value: baserow
  - name: COMPONENT
    value: backend
  - name: IMG_TAG
    value: latest
  - name: APP_PORT
    value: "8000"
  - name: APP_NAMESPACE
    value: 245e18-dev
  - name: WEB_FRONTEND_NAMESPACE
    value: 245e18-dev
  - name: WEB_FRONTEND_COMPONENT
    value: web-frontend
  - name: DOMAIN
    value: apps.silver.devops.gov.bc.ca
  - name: DATABASE_COMPONENT
    value: database
  - name: MJML_COMPONENT
    value: mjml
  - name: SRC_GIT_URL
    value: https://gitlab.com/bramw/baserow.git
  - description: Secret Key for the Application token generator.
    displayName: Secret Key
    from: "[a-zA-Z0-9]{24}"
    generate: expression
    name: SECRET_KEY
    required: true
objects:
  - apiVersion: v1
    kind: DeploymentConfig
    metadata:
      labels:
        app: ${APP}
        component: ${COMPONENT}
      name: ${APP}-${COMPONENT}
    spec:
      replicas: 1
      selector:
        app: ${APP}
        component: ${COMPONENT}
      strategy:
        type: Recreate
        recreateParams:
          timeoutSeconds: 900
          pre:
            failurePolicy: Retry
            execNewPod:
              command:
                - "python"
                - "/backend/src/baserow/manage.py"
                - "migrate"
            containerName: ${APP}-${COMPONENT}-migrate
        activeDeadlineSeconds: 21600
      template:
        metadata:
          labels:
            app: ${APP}
            component: ${COMPONENT}
        spec:
          # initContainers:
          #   - name: ${APP}-${DATABASE_COMPONENT}-ready
          #     image: postgres:10
          #     command: ['sh', '-c', 
          #       "until pg_isready -h ${APP}-${DATABASE_COMPONENT} -p 5432 -U postgres; 
          #       do echo waiting for database; sleep 2; done;"]
          containers:
            - env:
                - name: DATABASE_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      key: database-password
                      name: ${APP}-${DATABASE_COMPONENT}
                - name: DATABASE_HOST
                  value: ${APP}-${DATABASE_COMPONENT}
                - name: SECRET_KEY
                  value: "${SECRET_KEY}"
                - name: MJML_SERVER_HOST
                  value: ${APP}-${MJML_COMPONENT}
                - name: PUBLIC_WEB_FRONTEND_URL
                  value: https://${APP}-${WEB_FRONTEND_COMPONENT}-${WEB_FRONTEND_NAMESPACE}.${DOMAIN}
                - name: PUBLIC_BACKEND_URL
                  value: https://${APP}-${COMPONENT}-${APP_NAMESPACE}.${DOMAIN}
                - name: PRIVATE_BACKEND_URL
                  value: http://${APP}-${COMPONENT}:${APP_PORT}
              image: " "
              name: ${APP}-${COMPONENT}
              ports:
                - containerPort: ${{APP_PORT}}
              # livenessProbe:
              #   httpGet:
              #     path: "/_health"
              #     port: 3000
              #     scheme: HTTP
              #   initialDelaySeconds: 10
              #   timeoutSeconds: 2
              #   periodSeconds: 10
              #   successThreshold: 1
              #   failureThreshold: 10
          restartPolicy: Always
      test: false
      triggers:
        - type: ConfigChange
        - imageChangeParams:
            automatic: true
            containerNames:
              - ${APP}-${COMPONENT}
            from:
              kind: ImageStreamTag
              name: ${APP}-${COMPONENT}:${IMG_TAG}
          type: ImageChange
  - apiVersion: v1
    kind: Service
    metadata:
      labels:
        app: ${APP}
        component: ${COMPONENT}
      name: ${APP}-${COMPONENT}
    spec:
      ports:
        - name: ${APP_PORT}
          port: ${{APP_PORT}}
      selector:
        app: ${APP}
        component: ${COMPONENT}
  - apiVersion: v1
    kind: Route
    metadata:
      labels:
        app: ${APP}
        component: ${COMPONENT}
      name: ${APP}-${COMPONENT}
    spec:
      host: ${APP}-${COMPONENT}-${APP_NAMESPACE}.${DOMAIN}
      port:
        targetPort: ${{APP_PORT}}
      to:
        kind: Service
        name: ${APP}-${COMPONENT}
      tls:
        termination: edge
